### ISSUE TITLE
DSL-JSON v1.8.3

### ISSUE THREAD

**Issue by zapov** [ngs-doo/dsl-json#94] opened 2018-10-10 22:35 UTC
Is there something critical which should be fixed before next version?

@varahash I saw that examples behave somewhat strange... if you change something in Maven8 project and try to run it again it complains about: 

    Error:java: java.lang.NoClassDefFoundError: com/dslplatform/maven/Example$LocalTimeConverter

Thats one remaining thing I plan on looking into (not sure if it's due IntelliJ or recent changes).
Do you have any idea why it would behave like that?

Is there something you would like to go in before the release?

**Comment by zapov** [comment] 2018-10-12 05:43
This problem was introduced in this commit: https://github.com/ngs-doo/dsl-json/commit/3dc7ad5d0e661a1d54bd6b653b7d28672ad24ee9
@varahash can look look into fixing it?

**Comment by varahash** [comment] 2018-10-12 09:53
I can look into it on this weekend.

**Comment by varahash** [comment] 2018-10-12 18:36
The exception which I posted above, can be fixed in one of the ways: 
- update `maven-compiler-plugin` to the latest version (3.8.0)
- disable incremental compilation `<useIncrementalCompilation>false</useIncrementalCompilation>`

I was unable to reproduce your issue, but try one of these fixes.

**Comment by zapov** [comment] 2018-10-13 07:40
Neither of those fixed the issue I'm having ;(
I also tried upgrading maven from 3.3.9 to 3.5.4 and that didn't help either ;(

It seems Example* classes get deleted during recompilation and then something kicks in which cannot find the classes. I'm assuming it's some of those type resolutions but not sure where and why.

I actually partially reverted your changes (kept most of them and then it was working again)...

Ok, since you cannot reproduce it I'll look into it further...

**Comment by zapov** [comment] 2018-10-13 07:52
It's failing here:

```Caused by: java.lang.NoClassDefFoundError: com/dslplatform/maven/Example$LocalTimeConverter
	at dsl_json.java.time._LocalTime_DslJsonConverter.configure(_LocalTime_DslJsonConverter.java:7)
	at com.dslplatform.json.ExternalConverterAnalyzer.tryFindConverter(ExternalConverterAnalyzer.java:23)
	at com.dslplatform.json.DslJson.lookupFromFactories(DslJson.java:1054)
	at com.dslplatform.json.DslJson.tryFindWriter(DslJson.java:1012)
	at com.dslplatform.json.DslJson.canSerialize(DslJson.java:1366)
	at com.dslplatform.json.processor.CompiledJsonAnnotationProcessor.lambda$process$0(CompiledJsonAnnotationProcessor.java:233)
	at com.dslplatform.json.processor.CachedTypeSupport.isSupported(CachedTypeSupport.java:18)
	at com.dslplatform.json.processor.Analysis.analyzePartsRecursively(Analysis.java:1174)
	at com.dslplatform.json.processor.Analysis.analyzePartsRecursively(Analysis.java:1214)
	at com.dslplatform.json.processor.Analysis.analyzeParts(Analysis.java:1168)
	at com.dslplatform.json.processor.Analysis.analyzeAttribute(Analysis.java:717)
	at com.dslplatform.json.processor.Analysis.findRelatedReferences(Analysis.java:670)
	at com.dslplatform.json.processor.Analysis.processAnnotation(Analysis.java:156)
	at com.dslplatform.json.processor.CompiledJsonAnnotationProcessor.process(CompiledJsonAnnotationProcessor.java:272)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)```

But it seems it's calling into annotation processor *before* it compiled the Example classes (and there is leftover from previous java8 annotation processor compilation)

**Comment by varahash** [comment] 2018-10-13 09:14
Ok, I can reproduce your issue on JDK11. The fixes witch I posted above works for me.
What I did:
1) checkout last commit from master
2) update maven-compiler-plugin to 3.8.0 **or** disable incremental compilation
3) mvn clean of example project (this is **important** step)

After these steps everything works, you can compile and recompile without errors.

**Comment by varahash** [comment] 2018-10-13 10:48
On my machine (macOS 10.14, Maven 3.5.4) it fails with following error:
1) for JDK11
```
[ERROR] Failed creating compiled json serialization file dsl_json.java.time._LocalTime_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model$Concrete_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model$Abstract_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model$WithCustomCtor_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model$ViaFactory_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._ImmutablePerson_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._PersonBuilder_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._SpecialNumber_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model$ParentClass_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model$Nested_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model$State_DslJsonConverter
[ERROR] Failed creating compiled json serialization file com.dslplatform.maven._Example$Model$Interface_DslJsonConverter
```
2)  for JDK 1.8.0_181
```
An exception has occurred in the compiler (1.8.0_181). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.IllegalStateException: endPosTable already set
	at com.sun.tools.javac.util.DiagnosticSource.setEndPosTable(DiagnosticSource.java:136)
	at com.sun.tools.javac.util.Log.setEndPosTable(Log.java:350)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:667)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:950)
.
.
.
```
So we need also apply one of these fixes to fix my issue.

What is your OS, JDK, Maven version?

**Comment by zapov** [comment] 2018-10-13 10:55
:)
I've just released it. I did add v3.8.0 to some maven examples

Win7 (both Java8 and 11) On both maven 3.3.9 and 3.5.4
But I've fixed my issue with that catch

Try it now with latest version

**Comment by zapov** [comment] 2018-10-13 11:14
btw. that `endPosTable already set` looks like an old problem. If you can reproduce it consistently it would be good to report it upstream

**Comment by varahash** [comment] 2018-10-13 11:29
It is this bug https://bugs.java.com/view_bug.do?bug_id=8067747. They fixed it for JDK >= 9. 
Someone wrote in comment:

> To my knowledge, there are two aspects to this bug:
> 1) the javac bug that it crashes with an exception. I am working on this, but please note that javac won't compile the input when this is fixed, it will throw an appropriate exception from the Filer (see below).
> 
> 2) what appears to be a maven bug: when the project is compiled with "clean install", an annotation processor will generate a source file into "target/generated-sources/annotations". When the incremental compilation is done, this generated file is passed to javac as an input, and the annotation processor will try to generate it again, which is not allowed. Please see:
> https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Filer.html
> 
> In particular:
> {quote}
> During each run of an annotation processing tool, a file with a given pathname may be created only once. If that file already exists before the first attempt to create it, the old contents will be deleted. Any subsequent attempt to create the same file during a run will throw a FilerException, as will attempting to create both a class file and source file for the same type name or same package name. The initial inputs to the tool are considered to be created by the zeroth round; therefore, attempting to create a source or class file corresponding to one of those inputs will result in a FilerException.
> {quote}

**Closed** 2018-10-14 13:30 UTC
