### ISSUE TITLE
Unable to serialize List of Abstract Class

### ISSUE THREAD

**Issue by xStoneMountain** [ngs-doo/dsl-json#116] opened 2019-03-11 10:24 UTC
Tried the polymorphism example. unable to serialize List of abstract class. 

```
@CompiledJson(discriminator = "@type")
public abstract class AbstractClass {

	abstract int number();

	abstract String getName();

	//since name (deserializeName) is not specified $type:ClassName will be encoded in JSON so it can be correctly deserialized
	@CompiledJson
	public static class ImmutableImplementation extends AbstractClass {
		private final int number;
		private final String name;

		public int number() {
			return number;
		}

		public String getName() {
			return name;
		}

		public ImmutableImplementation(int number, String name) {
			this.number = number;
			this.name = name;
		}
	}
	
	//since name (deserializeName) is not specified $type:ClassName will be encoded in JSON so it can be correctly deserialized
	@CompiledJson
	public static class testImple extends AbstractClass {
		private final int number;
		private final String name;
		private final List<AbstractClass> list;

		public int number() {
			return number;
		}

		public String getName() {
			return name;
		}
		
		public List<AbstractClass> list() {
			return list;
		}


		public testImple(int number, String name,List<AbstractClass> list) {
			this.number = number;
			this.name = name;
			this.list = list;
		}
	}

```

```
DslJson<Object> dslJson = new DslJson<>();

		Model instance = new Model();
		instance.abstractProperty = new AbstractClass.ImmutableImplementation(5, "DSL");
		instance.abstractList = Arrays.asList(
				new AbstractClass.testImple(1, "speed", Arrays.asList( new AbstractClass.ImmutableImplementation(5, "DSLList"))),
				null,
				new AbstractClass.MutableImplementation().number(2).setName("features"));
		instance.ifaceProperty = new Interface.ImmutableImplementation(6, "JSON");
		instance.ifaceList = Arrays.asList(
				null,
				new Interface.ImmutableImplementation(1, "type safety"),
				new Interface.MutableImplementation().number(2).setName("transparency")
		);

```

```
Exception in thread "main" java.lang.NullPointerException
	at com.dslplatform.json.JsonWriter.serialize(JsonWriter.java:731)

```

**Comment by zapov** [comment] 2019-03-11 11:27
Are you trying to run the example from Eclipse?

I should put a disclaimer about Eclipse in the readme ;(

Please try from IDEA or directly from Maven, eg:

    mvn clean install exec:java -Dexec.mainClass="com.dslplatform.polymorphism.Example"

**Comment by xStoneMountain** [comment] 2019-03-12 02:31
Yes im using eclipse, Im able to execute the original example. I just tried to add another class extending the abstract class containing a list of the abstract class.

**Comment by zapov** [comment] 2019-03-12 04:39
Ah, I see. I managed to reproduce it. Tnx.

I guess I'll have to fallback to lazy initialization or initialize it somehow differently.

**Comment by xStoneMountain** [comment] 2019-03-18 03:53
Any workaround to create a map or list of a class with an object field .
Im trying out to serialize a model where the value is not limited to string only. hence I need to declare it as an object .

**Comment by zapov** [comment] 2019-03-18 09:45
You can override the default behavior by registering your own converter, eg:

    public static class CycleWorkaround implements Configuration {
        public static JsonReader.ReadObject<List<AbstractClass>> JSON_READER;
        public static JsonWriter.WriteObject<List<AbstractClass>> JSON_WRITER;

        @Override
        public void configure(DslJson dslJson) {
            JSON_READER = dslJson.tryFindReader(new TypeDefinition<List<AbstractClass>>(){}.type);
            JSON_WRITER = dslJson.tryFindWriter(new TypeDefinition<List<AbstractClass>>(){}.type);
        }
    }

Since service loader does not pick up this by default anymore ;( you'll have to register it during initialization:

    DslJson<Object> dslJson = new DslJson<>(
        Settings.withRuntime()
            .includeServiceLoader()
            .with(new AbstractClass.CycleWorkaround()));

Also, it seems you'll have to put discriminator on other classes as well, otherwise it will use $type with the current code.

I'll fix the cycle problem in v1.9.0

**Comment by zapov** [comment] 2019-03-22 07:48
This was fixed in last commit: https://github.com/ngs-doo/dsl-json/commit/356697a44915dc26a240351d83aee1e70895c68f

I'll look into releasing v1.9.0 next week

**Comment by zapov** [comment] 2019-03-30 21:04
v1.9.0 released
All relevant issues have been fixed

**Closed by zapov** 2019-03-30 21:04 UTC
