### ISSUE TITLE
@CompiledJson.namingStrategy doens't work

### ISSUE THREAD

**Issue by longdt** [ngs-doo/dsl-json#229] opened 2022-05-16 06:14 UTC
I have simple model class:
```
import com.dslplatform.json.CompiledJson;
import com.dslplatform.json.processor.MinifiedNaming;

@CompiledJson(namingStrategy = MinifiedNaming.class)
public class Order {
    private Long id;
    private String serviceCode;
    ..setter/getter methods
}
```

I'm trying implement snake case naming strategy but when compile code with MinifiedNaming I with get error message: 
`Unable to create an instance of NamingStrategy from the provided class: 'com.dslplatform.json.processor.MinifiedNaming'. class com.dslplatform.json.processor.MinifiedNaming cannot be cast to class com.dslplatform.json.processor.NamingStrategy (com.dslplatform.json.processor.MinifiedNaming is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @1704f67f; com.dslplatform.json.processor.NamingStrategy is in unnamed module of loader java.net.URLClassLoader @6240651f)`

To avoid class `com.dslplatform.json.processor.NamingStrategy` was loaded by different class loader. The following code:
Analysis.namingStrategy():
```
Class<?> manifest = Thread.currentThread().getContextClassLoader().loadClass(strategyName);
strategy = (NamingStrategy) manifest.newInstance();
```
should be:
```
Class<?> manifest = NamingStrategy.class.getClassLoader().loadClass(strategyName);
strategy = (NamingStrategy) manifest.getConstructor().newInstance();
```

dsl-json: 1.9.9

**Comment by zapov** [comment] 2022-05-16 15:44
It would be great if you had a reproducible.
The main reason it was trying to load from context class loader is because your custom jar would not be known by dsl-json jar where NaminStrategy is.
So I can surely change it to something better, but your suggestion looks like it will hit some other limitations :(
I remember when writing this that I wanted to use the same mechanism to load type via type mirrors, but gave up without trying too hard.

**Comment by longdt** [comment] 2022-06-09 10:53
@zapov you can check this repo: https://github.com/longdt/dsl-json-ext
I write this to provide snake case naming strategy. You can run test case inside module `test-functional`, but first you need remove some replaced DSL-JSON classes due I do some trick to workaround

**Comment by zapov** [comment] 2022-08-13 19:28
I merged a change which improves this. But I noticed that it wont work if you have this naming strategy in the same project/jar. Meaning it must be able to create instance of this class during compilation.

Anyway... I've made it like you suggested with a fallback to old version.

**Comment by zapov** [comment] 2023-01-07 08:43
v1.10 released

**Closed by zapov** 2023-01-07 08:43 UTC
