### ISSUE TITLE
BigIntegerConverter.readLongNumber() computes NumberInfo.length incorrect

### ISSUE THREAD

**Issue by longdt** [ngs-doo/dsl-json#234] opened 2022-06-07 09:20 UTC
I found something wrong in method `BigIntegerConverter.readLongNumber()`: 
```
private static NumberInfo readLongNumber(final JsonReader reader, final int start) throws IOException {
		int i = reader.length() - start;
		char[] tmp = reader.prepareBuffer(start, i);
		final long position = reader.positionInStream();
		while (!reader.isEndOfStream()) {
			while (i < tmp.length) {
				final char ch = (char) reader.read();
				tmp[i++] = ch;
				if (reader.isEndOfStream() || !(ch >= '0' && ch <= '9' || ch == '-' || ch == '+' || ch == '.' || ch == 'e' || ch == 'E')) {
					return new NumberInfo(tmp, i);
```
for example when use dsl-json to deserialize an input stream which contains big array json payload like this: `[<big integer 1>,<big integer 2>,<big integer n>]`.  At end of first block (default 4096 bytes) then function `readLongNumber` was call.
When variable `ch` = ',' the function should decrease JsonReader.currentIndex and  return `NumberInfo(tmp, --i)`
Dsl-json v1.9.9

**Comment by zapov** [comment] 2022-06-09 09:23
Tnx for the report. Ideally it would be to provide test case along the report.

**Comment by longdt** [comment] 2022-06-09 09:57
@zapov Test case is here: https://github.com/longdt/dsl-json-parse-number

**Comment by longdt** [comment] 2022-06-09 10:00
and this is my workaround:
```
public abstract class BigIntegerConverter {
    private static final VarHandle JSON_READER_CURRENT_INDEX;

    static {
        try {
            JSON_READER_CURRENT_INDEX = MethodHandles
                    .privateLookupIn(JsonReader.class, MethodHandles.lookup())
                    .findVarHandle(JsonReader.class, "currentIndex", int.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static NumberInfo readLongNumber(final JsonReader reader, final int start) throws IOException {
        int i = reader.length() - start;
        char[] tmp = reader.prepareBuffer(start, i);
        final long position = reader.positionInStream();
        while (!reader.isEndOfStream()) {
            while (i < tmp.length) {
                final char ch = (char) reader.read();
                tmp[i++] = ch;
                if (reader.isEndOfStream()) {
                    return new NumberInfo(tmp, i);
                } else if (!(ch >= '0' && ch <= '9' || ch == '-' || ch == '+' || ch == '.' || ch == 'e' || ch == 'E')) {
                    JSON_READER_CURRENT_INDEX.set(reader, reader.getCurrentIndex() - 1);
                    return new NumberInfo(tmp, --i);
                }
...
}
```

**Comment by zapov** [comment] 2022-07-17 12:18
Fixed on master. For some reason there was buggy duplicate of this long number parsing in BigInt.
I've deleted the buggy one and redirected it to one which works as expected.

btw. if you want to fix it on current version, you can just register custom implementation of BigInteger handling. That should fix it without the need for this hacks.

**Comment by zapov** [comment] 2023-01-07 08:43
v1.10 released

**Closed by zapov** 2023-01-07 08:43 UTC
